name: Nodejs Workflow with CRA

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

env:
  CI: ""

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install
      
      - name: Generate template
        uses: gacts/run-and-post-run@v1
        with:
          run: node index.js
          post: |
              echo "Post motem"
              cat logs/progress-$(date +'%Y-%m-%d').log

      - name: Install Template build dependencies
        working-directory: build
        run: yarn install

      - name: Build CRA
        working-directory: build
        run: yarn run build
