name: Nodejs Workflow with CRA

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

env:
  CI: ""

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (Project)
        run: yarn install
      
      - name: Generate template (Index)
        uses: gacts/run-and-post-run@v1
        with:
          run: node index.js
          post: |
              echo "Post motem"
              cat logs/progress-$(date +'%Y-%m-%d').log

      - name: Install build dependencies (Index)
        working-directory: build
        run: yarn install

      - name: Format code (Index)
        working-directory: build
        run: yarn run format

      - name: Build CRA (Index)
        working-directory: build
        run: yarn run build

      - name: Generate archive template (Local archive)
        uses: gacts/run-and-post-run@v1
        with:
          run: node index.js examples/index.zip
          post: |
              echo "Post motem"
              cat logs/progress-$(date +'%Y-%m-%d').log
      - name: Install build dependencies (Local archive)
        working-directory: build
        run: yarn install

      - name: Format code (Local archive)
        working-directory: build
        run: yarn run format

      - name: Build CRA (Local archive)
        working-directory: build
        run: yarn run build

      - name: Generate template (Online archive)
        uses: gacts/run-and-post-run@v1
        with:
          run: node index.js https://github.com/themewagon/mexant/archive/refs/tags/v1.0.0.zip
          post: |
              echo "Post motem"
              cat logs/progress-$(date +'%Y-%m-%d').log
      - name: Install build dependencies (Online archive)
        working-directory: build
        run: yarn install

      - name: Format code (Online archive)
        working-directory: build
        run: yarn run format

      - name: Build CRA (Online archive)
        working-directory: build
        run: yarn run build
